In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\Projects\User Funnel Analysis\Dataset\Funnel_Analysis_Data.csv")

In [9]:
df.head()

,User ID,Session ID,Event Time,Event,Device,Region,Channel,Product Category,Revenue,Bonus Flag
0,USR-00001,SES-00001,2026-01-07 23:46:20.358501,Browse,Tablet,South,Organic,Electronics,0.0,Yes
1,USR-00001,SES-00001,2026-01-07 23:49:20.358501,Add to Cart,Tablet,South,Organic,Electronics,0.0,Yes
2,USR-00001,SES-00001,2026-01-07 23:51:20.358501,Checkout,Tablet,South,Organic,Electronics,0.0,Yes
3,USR-00002,SES-00002,2026-01-04 21:06:42.296010,Browse,Desktop,East,Email,Sports,0.0,Yes
4,USR-00002,SES-00002,2026-01-04 21:10:42.296010,Add to Cart,Desktop,East,Email,Sports,0.0,Yes

In [5]:
df.columns.tolist()

['User ID',
 'Session ID',
 'Event Time',
 'Event',
 'Device',
 'Region',
 'Channel',
 'Product Category',
 'Revenue',
 'Bonus Flag']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21409 entries, 0 to 21408
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User ID           21409 non-null  object
 1   Session ID        21409 non-null  object
 2   Event Time        21409 non-null  object
 3   Event             21409 non-null  object
 4   Device            21409 non-null  object
 5   Region            21409 non-null  object
 6   Channel           21409 non-null  object
 7   Product Category  21409 non-null  object
 8   Revenue           21409 non-null  float64
 9   Bonus Flag        21409 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.6+ MB

In [14]:
df.describe()

            Revenue
count  21409.000000
mean      12.953574
std       65.005620
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max      499.990000

In [16]:
df.shape

(21409, 10)

In [18]:
df.isnull().sum()

User ID             0
Session ID          0
Event Time          0
Event               0
Device              0
Region              0
Channel             0
Product Category    0
Revenue             0
Bonus Flag          0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [22]:
df['Event'].value_counts()

Event
Browse         10000
Add to Cart     6949
Checkout        3456
Purchase        1004
Name: count, dtype: int64

In [24]:
df['Event Time'] = pd.to_datetime(df['Event Time'])

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21409 entries, 0 to 21408
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User ID           21409 non-null  object
 1   Session ID        21409 non-null  object
 2   Event Time        21409 non-null  datetime64[ns]
 3   Event             21409 non-null  object
 4   Device            21409 non-null  object
 5   Region            21409 non-null  object
 6   Channel           21409 non-null  object
 7   Product Category  21409 non-null  object
 8   Revenue           21409 non-null  float64
 9   Bonus Flag        21409 non-null  object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 1.6+ MB

In [26]:
df['Date'] = df['Event Time'].dt.date

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21409 entries, 0 to 21408
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User ID           21409 non-null  object
 1   Session ID        21409 non-null  object
 2   Event Time        21409 non-null  datetime64[ns]
 3   Event             21409 non-null  object
 4   Device            21409 non-null  object
 5   Region            21409 non-null  object
 6   Channel           21409 non-null  object
 7   Product Category  21409 non-null  object
 8   Revenue           21409 non-null  float64
 9   Bonus Flag        21409 non-null  object
 10  Date              21409 non-null  object
dtypes: datetime64[ns](1), float64(1), object(9)
memory usage: 1.8+ MB

In [30]:
df['Month'] = df['Event Time'].dt.month_name()
df['Day'] = df['Event Time'].dt.day_name()
df['Hour'] = df['Event Time'].dt.hour

In [31]:
df.head()

,User ID,Session ID,Event Time,Event,Device,Region,Channel,Product Category,Revenue,Bonus Flag,Date,Month,Day,Hour
0,USR-00001,SES-00001,2026-01-07 23:46:20.358501,Browse,Tablet,South,Organic,Electronics,0.0,Yes,2026-01-07,January,Wednesday,23
1,USR-00001,SES-00001,2026-01-07 23:49:20.358501,Add to Cart,Tablet,South,Organic,Electronics,0.0,Yes,2026-01-07,January,Wednesday,23
2,USR-00001,SES-00001,2026-01-07 23:51:20.358501,Checkout,Tablet,South,Organic,Electronics,0.0,Yes,2026-01-07,January,Wednesday,23
3,USR-00002,SES-00002,2026-01-04 21:06:42.296010,Browse,Desktop,East,Email,Sports,0.0,Yes,2026-01-04,January,Sunday,21
4,USR-00002,SES-00002,2026-01-04 21:10:42.296010,Add to Cart,Desktop,East,Email,Sports,0.0,Yes,2026-01-04,January,Sunday,21

In [35]:
df['Device'].value_counts()

Device
Desktop    7271
Tablet     7190
Mobile     6948
Name: count, dtype: int64

In [36]:
df['Region'].value_counts()

Region
South    5466
East     5397
West     5278
North    5268
Name: count, dtype: int64

In [37]:
df['Channel'].value_counts()

Channel
Google Ads      5427
Email           5404
Organic         5378
Social Media    5200
Name: count, dtype: int64

In [38]:
df['Product Category'].value_counts()

Product Category
Electronics    4435
Beauty         4353
Fashion        4289
Home           4185
Sports         4147
Name: count, dtype: int64

In [39]:
df['Revenue'].describe()

count    21409.000000
mean        12.953574
std         65.005620
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        499.990000
Name: Revenue, dtype: float64

In [40]:
df.groupby('Event')['User ID'].nunique()

Event
Add to Cart     6949
Browse         10000
Checkout        3456
Purchase        1004
Name: User ID, dtype: int64

In [41]:
pd.crosstab(df['Device'], df['Event'])

Event    Add to Cart  Browse  Checkout  Purchase
Device
Desktop         2367    3366      1182       356
Mobile          2253    3263      1123       309
Tablet          2329    3371      1151       339

In [42]:
pd.crosstab(df['Channel'], df['Event'])

Event         Add to Cart  Browse  Checkout  Purchase
Channel
Email                1762    2515       879       248
Google Ads           1746    2520       893       268
Organic              1745    2528       866       239
Social Media         1696    2437       818       249

In [43]:
 pd.crosstab(df['Product Category'],df['Event'])

Event             Add to Cart  Browse  Checkout  Purchase
Product Category
Beauty                   1428    2021       713       191
Electronics              1443    2052       711       229
Fashion                  1385    2001       692       211
Home                     1357    1978       666       184
Sports                   1336    1948       674       189

In [44]:
pd.crosstab(df['Region'], df['Event'])

Event   Add to Cart  Browse  Checkout  Purchase
Region
East           1744    2548       860       245
North          1708    2463       844       253
South          1782    2543       873       268
West           1715    2446       879       238

In [45]:
pd.crosstab(df['Bonus Flag'], df['Event'])

Event       Add to Cart  Browse  Checkout  Purchase
Bonus Flag
No                    0       0         0      1004
Yes                6949   10000      3456         0

In [46]:
df.groupby(['Bonus Flag','Event']).size()

Bonus Flag  Event
No          Purchase        1004
Yes         Add to Cart     6949
            Browse         10000
            Checkout        3456
dtype: int64

In [47]:
df['Bonus Flag'].value_counts()

Bonus Flag
Yes    20405
No      1004
Name: count, dtype: int64

In [48]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [49]:
df.columns

Index(['user_id', 'session_id', 'event_time', 'event', 'device', 'region',
       'channel', 'product_category', 'revenue', 'bonus_flag', 'date', 'month',
       'day', 'hour'],
      dtype='object')

In [51]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"
password = "6396"
host = "localhost"
port = "5432"
database = "user_funnel_analysis"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL
# this creates table automatically
df.to_sql(
    name='user_funnel',
    con=engine,
    if_exists='replace',
    index=False
)

409